FROM php:8.2-fpm

# If opcache.ini exists, modify it:
RUN if [ -f $PHP_INI_DIR/conf.d/opcache.ini ]; then \
    sed -i 's/opcache.enable=1/opcache.enable=0/' $PHP_INI_DIR/conf.d/opcache.ini; \
fi

# If not, create it:
RUN if [ ! -f $PHP_INI_DIR/conf.d/opcache.ini ]; then \
    echo "opcache.enable=0" > $PHP_INI_DIR/conf.d/opcache.ini; \
fi

USER root
